### ISSUE TITLE
Error updating @

### ISSUE THREAD

**Issue by frod0** [thatjpk/cloudflare-ddns#15]
i got this error when i try to update the root domain
Traceback (most recent call last):
  File "/opt/cloudflare-ddns/cloudflare_ddns.py", line 188, in <module>
    main()
  File "/opt/cloudflare-ddns/cloudflare_ddns.py", line 168, in main
    raise Exception(msg)
Exception: Updating record failed with the result 'error'

**Comment by thatjpk** [comment]
If you're updating 'foo.com', and you set both cf_domain and cf_subdomain to 'foo.com', it'll update the A record you're after.

**Comment by frod0** [comment]
It works! thanks!

**Comment by thatjpk** [comment]
🎉
